[package]
name = "ini"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
configparser = "3.0.3"
